module.exports = {
    font: {
        size: {
            base: { value: '1rem' },
            h1: { value: '3rem' },
            'h1-mobile': { value: '2.5rem' },
            h2: { value: '2.5rem' },
            'h2-mobile': { value: '2.25rem' },
            h3: { value: '2.25rem' },
            'h3-mobile': { value: '2rem' },
            h4: { value: '1.75rem' },
            'h4-mobile': { value: '1.625rem' },
            h5: { value: '1.5rem' },
            'h5-mobile': { value: '1.375rem' },
            h6: { value: '1.25rem' },
            'h6-mobile': { value: '1.125rem' },
            t1: { value: '2rem' },
            't1-mobile': { value: '1.75rem' },
            t2: { value: '1.5rem' },
            't2-mobile': { value: '1.5rem' },
            p1: { value: '1rem' },
            p2: { value: '1rem' },
            p3: { value: '0.875rem' },
            'p3-mobile': { value: '0.75rem' },
            e1: { value: '1.875rem' },
            'e1-mobile': { value: '2rem' }
        },
    },
    height: {
        base: { value: '1rem' },
        h1: { value: '3.625rem' },
        'h1-mobile': { value: '3.125rem' },
        h2: { value: '3.125rem' },
        'h2-mobile': { value: '2.75rem' },
        h3: { value: '2.875rem' },
        'h3-mobile': { value: '2.625rem' },
        h4: { value: '2.25rem' },
        'h4-mobile': { value: '2.125rem' },
        h5: { value: '2rem' },
        'h5-mobile': { value: '1.875rem' },
        h6: { value: '2rem' },
        'h6-mobile': { value: '1.875rem' },
        t1: { value: '2.25rem' },
        't1-mobile': { value: '1.875rem' },
        t2: { value: '2rem' },
        't2-mobile': { value: '2rem' },
        p1: { value: '1.5rem' },
        p2: { value: '1.5rem' },
        p3: { value: '1.375rem' },
        'p3-mobile': { value: '1.25rem' },
        e1: { value: '2.125rem' },
        'e1-mobile': { value: '2rem' }
    }
};