Element.prototype.matches||(Element.prototype.matches=Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector);Element.prototype.closest||(Element.prototype.closest=function(A){var l=this;if(!document.documentElement.contains(l))return null;do{if(l.matches(A))return l;l=l.parentElement||l.parentNode}while(null!==l&&1===l.nodeType);return null});
(function(){function A(m){function F(n){t._config=n;n.element.removeAttribute("data-cmp-is");M(n.options);I(n.element);t._elements.item&&(t._elements.item=Array.isArray(t._elements.item)?t._elements.item:[t._elements.item],t._elements.button=Array.isArray(t._elements.button)?t._elements.button:[t._elements.button],t._elements.panel=Array.isArray(t._elements.panel)?t._elements.panel:[t._elements.panel],t._properties.singleExpansion&&(n=z(),1<n.length&&v(n.length-1)),r(),c(),J());window.Granite&&window.Granite.author&&
window.Granite.author.MessageChannel&&(window.CQ.CoreComponents.MESSAGE_CHANNEL=window.CQ.CoreComponents.MESSAGE_CHANNEL||new window.Granite.author.MessageChannel("cqauthor",window),window.CQ.CoreComponents.MESSAGE_CHANNEL.subscribeRequestMessage("cmp.panelcontainer",function(w){if(w.data&&"cmp-accordion"===w.data.type&&w.data.id===t._elements.self.dataset.cmpPanelcontainerId&&"navigate"===w.data.operation){var b=t._properties.singleExpansion;t._properties.singleExpansion=!0;v(w.data.index);t._properties.singleExpansion=
b}}))}function J(){if(f){var n=f.getDeepLinkItemIdx(t,"item","item");if(-1<n){if((n=t._elements.item[n])&&!n.hasAttribute(d.item.expanded)){if(t._properties.singleExpansion)for(var w=0;w<t._elements.item.length;w++)t._elements.item[w].hasAttribute(d.item.expanded)&&x(t._elements.item[w],!1,!0);x(n,!0,!0)}(n=window.location.hash.substring(1))&&(n=document.querySelector("[id\x3d'"+n+"']"))&&n.scrollIntoView()}}}function I(n){t._elements={};t._elements.self=n;n=t._elements.self.querySelectorAll("[data-cmp-hook-accordion]");
for(var w=0;w<n.length;w++){var b=n[w];if(b.closest(".cmp-accordion")===t._elements.self){var h="accordion";h=h.charAt(0).toUpperCase()+h.slice(1);h=b.dataset["cmpHook"+h];t._elements[h]?(Array.isArray(t._elements[h])||(t._elements[h]=[t._elements[h]]),t._elements[h].push(b)):t._elements[h]=b}}}function M(n){t._properties={};for(var w in q)if(Object.prototype.hasOwnProperty.call(q,w)){var b=q[w],h=null;n&&null!=n[w]&&(h=n[w],b&&"function"===typeof b.transform&&(h=b.transform(h)));null===h&&(h=q[w]["default"]);
t._properties[w]=h}}function c(){window.addEventListener("hashchange",J,!1);var n=t._elements.button;if(n)for(var w=0;w<n.length;w++)(function(b){n[w].addEventListener("click",function(h){v(b);K(b)});n[w].addEventListener("keydown",function(h){var y=t._elements.button.length-1;switch(h.keyCode){case p.ARROW_LEFT:case p.ARROW_UP:h.preventDefault();0<b&&K(b-1);break;case p.ARROW_RIGHT:case p.ARROW_DOWN:h.preventDefault();b<y&&K(b+1);break;case p.HOME:h.preventDefault();K(0);break;case p.END:h.preventDefault();
K(y);break;case p.ENTER:case p.SPACE:h.preventDefault(),v(b),K(b)}})})(w)}function v(n){if(n=t._elements.item[n]){if(t._properties.singleExpansion)for(var w=0;w<t._elements.item.length;w++)t._elements.item[w]!==n&&B(t._elements.item[w])&&x(t._elements.item[w],!1);x(n,!B(n));if(k){n=t._elements.self.id;var b=z().map(function(h){return u(h)});w={component:{}};w.component[n]={shownItems:b};b={component:{}};b.component[n]={shownItems:void 0};e.push(b);e.push(w)}}}function x(n,w,b){w?(n.setAttribute(d.item.expanded,
""),w=t._elements.item.indexOf(n),!b&&f&&f.updateUrlHash(t,"item",w),k&&e.push({event:"cmp:show",eventInfo:{path:"component."+u(n)}})):(n.removeAttribute(d.item.expanded),!b&&f&&f.removeUrlHash(),k&&e.push({event:"cmp:hide",eventInfo:{path:"component."+u(n)}}));B(n)?E(n):C(n)}function B(n){return n&&n.dataset&&void 0!==n.dataset.cmpExpanded}function r(){for(var n=0;n<t._elements.item.length;n++){var w=t._elements.item[n];B(w)?E(w):C(w)}}function z(){for(var n=[],w=0;w<t._elements.item.length;w++){var b=
t._elements.item[w];B(b)&&n.push(b)}return n}function E(n){n=t._elements.item.indexOf(n);if(-1<n){var w=t._elements.button[n];n=t._elements.panel[n];w.classList.add(a.button.expanded);setTimeout(function(){w.setAttribute("aria-expanded",!0)},100);n.classList.add(a.panel.expanded);n.classList.remove(a.panel.hidden);n.setAttribute("aria-hidden",!1)}}function C(n){n=t._elements.item.indexOf(n);if(-1<n){var w=t._elements.button[n];n=t._elements.panel[n];w.classList.remove(a.button.expanded);setTimeout(function(){w.setAttribute("aria-expanded",
!1)},100);n.classList.add(a.panel.hidden);n.classList.remove(a.panel.expanded);n.setAttribute("aria-hidden",!0)}}function K(n){t._elements.button[n].focus()}var t=this;m&&m.element&&F(m)}function l(m){m=m.dataset;var F=[],J="accordion";J=J.charAt(0).toUpperCase()+J.slice(1);J=["is","hook"+J];for(var I in m)if(Object.prototype.hasOwnProperty.call(m,I)){var M=m[I];0===I.indexOf("cmp")&&(I=I.slice(3),I=I.charAt(0).toLowerCase()+I.substring(1),-1===J.indexOf(I)&&(F[I]=M))}return F}function u(m){return m?
m.dataset.cmpDataLayer?Object.keys(JSON.parse(m.dataset.cmpDataLayer))[0]:m.id:null}function D(){e=(k=document.body.hasAttribute("data-cmp-data-layer-enabled"))?window.adobeDataLayer=window.adobeDataLayer||[]:void 0;for(var m=document.querySelectorAll(g.self),F=0;F<m.length;F++)new A({element:m[F],options:l(m[F])});m=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;F=document.querySelector("body");(new m(function(J){J.forEach(function(I){I=[].slice.call(I.addedNodes);
0<I.length&&I.forEach(function(M){M.querySelectorAll&&[].slice.call(M.querySelectorAll(g.self)).forEach(function(c){new A({element:c,options:l(c)})})})})})).observe(F,{subtree:!0,childList:!0,characterData:!0})}var f=window.CQ&&window.CQ.CoreComponents&&window.CQ.CoreComponents.container&&window.CQ.CoreComponents.container.utils?window.CQ.CoreComponents.container.utils:void 0;f||console.warn("Accordion: container utilities at window.CQ.CoreComponents.container.utils are not available. This can lead to missing features. Ensure the core.wcm.components.commons.site.container client library is included on the page.");
var k,e,p={ENTER:13,SPACE:32,END:35,HOME:36,ARROW_LEFT:37,ARROW_UP:38,ARROW_RIGHT:39,ARROW_DOWN:40},g={self:'[data-cmp-is\x3d"accordion"]'},a={button:{disabled:"cmp-accordion__button--disabled",expanded:"cmp-accordion__button--expanded"},panel:{hidden:"cmp-accordion__panel--hidden",expanded:"cmp-accordion__panel--expanded"}},d={item:{expanded:"data-cmp-expanded"}},q={singleExpansion:{"default":!1,transform:function(m){return!(null===m||"undefined"===typeof m)}}};"loading"!==document.readyState?D():
document.addEventListener("DOMContentLoaded",D);f&&window.addEventListener("load",f.scrollToAnchor,!1)})();Element.prototype.matches||(Element.prototype.matches=Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector);Element.prototype.closest||(Element.prototype.closest=function(A){var l=this;if(!document.documentElement.contains(l))return null;do{if(l.matches(A))return l;l=l.parentElement||l.parentNode}while(null!==l&&1===l.nodeType);return null});
(function(){function A(a){function d(v){c._config=v;v.element.removeAttribute("data-cmp-is");F(v.element);c._active=m(c._elements.tab);c._elements.tabpanel&&(I(),J(),q());window.Granite&&window.Granite.author&&window.Granite.author.MessageChannel&&(CQ.CoreComponents.MESSAGE_CHANNEL=CQ.CoreComponents.MESSAGE_CHANNEL||new window.Granite.author.MessageChannel("cqauthor",window),CQ.CoreComponents.MESSAGE_CHANNEL.subscribeRequestMessage("cmp.panelcontainer",function(x){x.data&&"cmp-tabs"===x.data.type&&
x.data.id===c._elements.self.dataset.cmpPanelcontainerId&&"navigate"===x.data.operation&&(c._active=x.data.index,I())}))}function q(){if(f){var v=f.getDeepLinkItemIdx(c,"tab","tabpanel");if(-1<v){var x=c._elements.tab[v];x&&c._elements.tab[c._active].id!==x.id&&M(v,!0);(v=window.location.hash.substring(1))&&(v=document.querySelector("[id\x3d'"+v+"']"))&&v.scrollIntoView()}}}function m(v){if(v)for(var x=0;x<v.length;x++)if(v[x].classList.contains(g.active.tab))return x;return 0}function F(v){c._elements=
{};c._elements.self=v;v=c._elements.self.querySelectorAll("[data-cmp-hook-tabs]");for(var x=0;x<v.length;x++){var B=v[x];if(B.closest(".cmp-tabs")===c._elements.self){var r="tabs";r=r.charAt(0).toUpperCase()+r.slice(1);r=B.dataset["cmpHook"+r];c._elements[r]?(Array.isArray(c._elements[r])||(c._elements[r]=[c._elements[r]]),c._elements[r].push(B)):c._elements[r]=B}}}function J(){window.addEventListener("hashchange",q,!1);var v=c._elements.tab;if(v)for(var x=0;x<v.length;x++)(function(B){v[x].addEventListener("click",
function(r){M(B)});v[x].addEventListener("keydown",function(r){var z=c._active,E=c._elements.tab.length-1;switch(r.keyCode){case p.ARROW_LEFT:case p.ARROW_UP:r.preventDefault();0<z&&M(z-1);break;case p.ARROW_RIGHT:case p.ARROW_DOWN:r.preventDefault();z<E&&M(z+1);break;case p.HOME:r.preventDefault();M(0);break;case p.END:r.preventDefault(),M(E)}})})(x)}function I(){var v=c._elements.tabpanel,x=c._elements.tab;if(v)if(Array.isArray(v))for(var B=0;B<v.length;B++)B===parseInt(c._active)?(v[B].classList.add(g.active.tabpanel),
v[B].removeAttribute("aria-hidden"),x[B].classList.add(g.active.tab),x[B].setAttribute("aria-selected",!0),x[B].setAttribute("tabindex","0")):(v[B].classList.remove(g.active.tabpanel),v[B].setAttribute("aria-hidden",!0),x[B].classList.remove(g.active.tab),x[B].setAttribute("aria-selected",!1),x[B].setAttribute("tabindex","-1"));else v.classList.add(g.active.tabpanel),x.classList.add(g.active.tab)}function M(v,x){var B=c._active;!x&&f&&f.updateUrlHash(c,"tab",v);c._active=v;I();x=window.scrollX||window.pageXOffset;
var r=window.scrollY||window.pageYOffset;c._elements.tab[v].focus();window.scrollTo(x,r);k&&(v=u(c._elements.tabpanel[v]),B=u(c._elements.tabpanel[B]),e.push({event:"cmp:show",eventInfo:{path:"component."+v}}),e.push({event:"cmp:hide",eventInfo:{path:"component."+B}}),B=c._elements.self.id,x={component:{}},x.component[B]={shownItems:[v]},v={component:{}},v.component[B]={shownItems:void 0},e.push(v),e.push(x))}var c=this;a&&a.element&&d(a)}function l(a){a=a.dataset;var d=[],q="tabs";q=q.charAt(0).toUpperCase()+
q.slice(1);q=["is","hook"+q];for(var m in a)if(Object.prototype.hasOwnProperty.call(a,m)){var F=a[m];0===m.indexOf("cmp")&&(m=m.slice(3),m=m.charAt(0).toLowerCase()+m.substring(1),-1===q.indexOf(m)&&(d[m]=F))}return d}function u(a){return a?a.dataset.cmpDataLayer?Object.keys(JSON.parse(a.dataset.cmpDataLayer))[0]:a.id:null}function D(){e=(k=document.body.hasAttribute("data-cmp-data-layer-enabled"))?window.adobeDataLayer=window.adobeDataLayer||[]:void 0;for(var a=document.querySelectorAll(g.self),
d=0;d<a.length;d++)new A({element:a[d],options:l(a[d])});a=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;d=document.querySelector("body");(new a(function(q){q.forEach(function(m){m=[].slice.call(m.addedNodes);0<m.length&&m.forEach(function(F){F.querySelectorAll&&[].slice.call(F.querySelectorAll(g.self)).forEach(function(J){new A({element:J,options:l(J)})})})})})).observe(d,{subtree:!0,childList:!0,characterData:!0})}var f=window.CQ&&window.CQ.CoreComponents&&window.CQ.CoreComponents.container&&
window.CQ.CoreComponents.container.utils?window.CQ.CoreComponents.container.utils:void 0;f||console.warn("Tabs: container utilities at window.CQ.CoreComponents.container.utils are not available. This can lead to missing features. Ensure the core.wcm.components.commons.site.container client library is included on the page.");var k,e,p={END:35,HOME:36,ARROW_LEFT:37,ARROW_UP:38,ARROW_RIGHT:39,ARROW_DOWN:40},g={self:'[data-cmp-is\x3d"tabs"]',active:{tab:"cmp-tabs__tab--active",tabpanel:"cmp-tabs__tabpanel--active"}};
"loading"!==document.readyState?D():document.addEventListener("DOMContentLoaded",D);f&&window.addEventListener("load",f.scrollToAnchor,!1)})();
(function(A){window.CMP=window.CMP||{};window.CMP.utils=function(){return{readData:function(l,u){l=l.dataset;var D=[];u=u.charAt(0).toUpperCase()+u.slice(1);u=["is","hook"+u];for(var f in l)if(Object.prototype.hasOwnProperty.call(l,f)){var k=l[f];0===f.indexOf("cmp")&&(f=f.slice(3),f=f.charAt(0).toLowerCase()+f.substring(1),-1===u.indexOf(f)&&(D[f]=k))}return D},setupProperties:function(l,u){var D={},f;for(f in u)if(Object.prototype.hasOwnProperty.call(u,f)){var k=u[f];D[f]=l&&null!=l[f]?k&&"function"===
typeof k.transform?k.transform(l[f]):l[f]:u[f]["default"]}return D}}}()})(window.document);
(function(){function A(g){function a(h){b._config=h;h.element.removeAttribute("data-cmp-is");m(h.options);q(h.element);b._active=0;b._paused=!1;b._elements.item&&(z(),F(),t(),r(),d());window.Granite&&window.Granite.author&&window.Granite.author.MessageChannel&&(window.CQ=window.CQ||{},window.CQ.CoreComponents=window.CQ.CoreComponents||{},window.CQ.CoreComponents.MESSAGE_CHANNEL=window.CQ.CoreComponents.MESSAGE_CHANNEL||new window.Granite.author.MessageChannel("cqauthor",window),window.CQ.CoreComponents.MESSAGE_CHANNEL.subscribeRequestMessage("cmp.panelcontainer",
function(y){y.data&&"cmp-carousel"===y.data.type&&y.data.id===b._elements.self.dataset.cmpPanelcontainerId&&"navigate"===y.data.operation&&C(y.data.index)}))}function d(){if(u){var h=u.getDeepLinkItemIdx(b,"item","item");if(-1<h){var y=b._elements.item[h];y&&b._elements.item[b._active].id!==y.id&&(K(h,!0),x());(h=window.location.hash.substring(1))&&(h=document.querySelector("[id\x3d'"+h+"']"))&&h.scrollIntoView()}}}function q(h){b._elements={};b._elements.self=h;h=b._elements.self.querySelectorAll("[data-cmp-hook-carousel]");
for(var y=0;y<h.length;y++){var G=h[y],H="carousel";H=H.charAt(0).toUpperCase()+H.slice(1);H=G.dataset["cmpHook"+H];b._elements[H]?(Array.isArray(b._elements[H])||(b._elements[H]=[b._elements[H]]),b._elements[H].push(G)):b._elements[H]=G}}function m(h){b._properties={};for(var y in e)if(Object.prototype.hasOwnProperty.call(e,y)){var G=e[y],H=null;h&&null!=h[y]&&(H=h[y],G&&"function"===typeof G.transform&&(H=G.transform(H)));null===H&&(H=e[y]["default"]);b._properties[y]=H}}function F(){window.addEventListener("hashchange",
d,!1);b._elements.previous&&b._elements.previous.addEventListener("click",function(){var L=0===b._active?b._elements.item.length-1:b._active-1;C(L);D&&f.push({event:"cmp:show",eventInfo:{path:"component."+l(b._elements.item[L])}})});b._elements.next&&b._elements.next.addEventListener("click",function(){var L=E();C(L);D&&f.push({event:"cmp:show",eventInfo:{path:"component."+l(b._elements.item[L])}})});var h=b._elements.indicator;if(h)for(var y=0;y<h.length;y++)(function(L){h[y].addEventListener("click",
function(N){K(L);x()})})(y);b._elements.pause&&b._properties.autoplay&&b._elements.pause.addEventListener("click",c);b._elements.play&&b._properties.autoplay&&b._elements.play.addEventListener("click",v);b._elements.self.addEventListener("keydown",J);b._properties.autopauseDisabled||(b._elements.self.addEventListener("mouseenter",I),b._elements.self.addEventListener("mouseleave",M));var G=b._elements.item;if(G)for(var H=0;H<G.length;H++)G[H].addEventListener("focusin",I),G[H].addEventListener("focusout",
M)}function J(h){var y=b._active,G=b._elements.indicator.length-1;switch(h.keyCode){case k.ARROW_LEFT:case k.ARROW_UP:h.preventDefault();0<y&&K(y-1);break;case k.ARROW_RIGHT:case k.ARROW_DOWN:h.preventDefault();y<G&&K(y+1);break;case k.HOME:h.preventDefault();K(0);break;case k.END:h.preventDefault();K(G);break;case k.SPACE:b._properties.autoplay&&h.target!==b._elements.previous&&h.target!==b._elements.next&&(h.preventDefault(),b._paused?B():x()),h.target===b._elements.pause&&b._elements.play.focus(),
h.target===b._elements.play&&b._elements.pause.focus()}}function I(h){n()}function M(h){t()}function c(h){x();b._elements.play.focus()}function v(){B();b._elements.pause.focus()}function x(){b._paused=!0;n();r()}function B(){var h=b._paused=!1;b._elements.self.parentElement&&(h=b._elements.self.parentElement.querySelector(":hover")===b._elements.self);!b._properties.autopauseDisabled&&h||t();r()}function r(){w(b._elements.pause,b._paused);w(b._elements.play,!b._paused)}function z(){var h=b._elements.item;
if(h&&Array.isArray(h))for(var y=0;y<h.length;y++)if(h[y].classList.contains("cmp-carousel__item--active")){b._active=y;break}}function E(){return b._active===b._elements.item.length-1?0:b._active+1}function C(h,y){if(!(0>h||h>b._elements.item.length-1)){b._active=h;var G=b._elements.item,H=b._elements.indicator;if(G)if(Array.isArray(G))for(var L=0;L<G.length;L++)L===parseInt(b._active)?(G[L].classList.add("cmp-carousel__item--active"),G[L].removeAttribute("aria-hidden"),H[L].classList.add("cmp-carousel__indicator--active"),
H[L].setAttribute("aria-selected",!0),H[L].setAttribute("tabindex","0")):(G[L].classList.remove("cmp-carousel__item--active"),G[L].setAttribute("aria-hidden",!0),H[L].classList.remove("cmp-carousel__indicator--active"),H[L].setAttribute("aria-selected",!1),H[L].setAttribute("tabindex","-1"));else G.classList.add("cmp-carousel__item--active"),H.classList.add("cmp-carousel__indicator--active");!y&&u&&u.updateUrlHash(b,"item",h);D&&(y=b._elements.self.id,G=l(b._elements.item[h]),h={component:{}},h.component[y]=
{shownItems:[G]},G={component:{}},G.component[y]={shownItems:void 0},f.push(G),f.push(h));b._elements.self.parentElement&&b._elements.self.parentElement.querySelector(":hover")!==b._elements.self&&t()}}function K(h,y){C(h,y);y=window.scrollX||window.pageXOffset;var G=window.scrollY||window.pageYOffset;b._elements.indicator[h].focus();window.scrollTo(y,G);D&&f.push({event:"cmp:show",eventInfo:{path:"component."+l(b._elements.item[h])}})}function t(){!b._paused&&b._properties.autoplay&&(n(),b._autoplayIntervalId=
window.setInterval(function(){if(!document.visibilityState||!document.hidden){var h=b._elements.indicators;h!==document.activeElement&&h.contains(document.activeElement)?K(E(),!0):C(E(),!0)}},b._properties.delay))}function n(){window.clearInterval(b._autoplayIntervalId);b._autoplayIntervalId=null}function w(h,y){h&&(!1!==y?(h.disabled=!0,h.classList.add("cmp-carousel__action--disabled")):(h.disabled=!1,h.classList.remove("cmp-carousel__action--disabled")))}var b=this;g&&g.element&&a(g)}function l(g){return g?
g.dataset.cmpDataLayer?Object.keys(JSON.parse(g.dataset.cmpDataLayer))[0]:g.id:null}var u=window.CQ&&window.CQ.CoreComponents&&window.CQ.CoreComponents.container&&window.CQ.CoreComponents.container.utils?window.CQ.CoreComponents.container.utils:void 0;u||console.warn("Tabs: container utilities at window.CQ.CoreComponents.container.utils are not available. This can lead to missing features. Ensure the core.wcm.components.commons.site.container client library is included on the page.");var D,f,k={SPACE:32,
END:35,HOME:36,ARROW_LEFT:37,ARROW_UP:38,ARROW_RIGHT:39,ARROW_DOWN:40},e={autoplay:{"default":!1,transform:function(g){return!(null===g||"undefined"===typeof g)}},delay:{"default":5E3,transform:function(g){g=parseFloat(g);return isNaN(g)?null:g}},autopauseDisabled:{"default":!1,transform:function(g){return!(null===g||"undefined"===typeof g)}}},p="loading"!==document.readyState?Promise.resolve():new Promise(function(g){document.addEventListener("DOMContentLoaded",g)});Promise.all([p]).then(function(){f=
(D=document.body.hasAttribute("data-cmp-data-layer-enabled"))?window.adobeDataLayer=window.adobeDataLayer||[]:void 0;for(var g=document.querySelectorAll('[data-cmp-is\x3d"carousel"]'),a=0;a<g.length;a++)new A({element:g[a],options:CMP.utils.readData(g[a],"carousel")});g=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;a=document.querySelector("body");(new g(function(d){d.forEach(function(q){q=[].slice.call(q.addedNodes);0<q.length&&q.forEach(function(m){m.querySelectorAll&&
[].slice.call(m.querySelectorAll('[data-cmp-is\x3d"carousel"]')).forEach(function(F){new A({element:F,options:CMP.utils.readData(F,"carousel")})})})})})).observe(a,{subtree:!0,childList:!0,characterData:!0})});u&&window.addEventListener("load",u.scrollToAnchor,!1)})();window.Element&&!Element.prototype.closest&&(Element.prototype.closest=function(A){A=(this.document||this.ownerDocument).querySelectorAll(A);var l=this,u;do for(u=A.length;0<=--u&&A.item(u)!==l;);while(0>u&&(l=l.parentElement));return l});
window.Element&&!Element.prototype.matches&&(Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector||Element.prototype.webkitMatchesSelector||function(A){A=(this.document||this.ownerDocument).querySelectorAll(A);for(var l=A.length;0<=--l&&A.item(l)!==this;);return-1<l});
Object.assign||(Object.assign=function(A,l){if(null===A)throw new TypeError("Cannot convert undefined or null to object");for(var u=Object(A),D=1;D<arguments.length;D++){var f=arguments[D];if(null!==f)for(var k in f)Object.prototype.hasOwnProperty.call(f,k)&&(u[k]=f[k])}return u});
(function(A){A.forEach(function(l){Object.prototype.hasOwnProperty.call(l,"remove")||Object.defineProperty(l,"remove",{configurable:!0,enumerable:!0,writable:!0,value:function(){this.parentNode.removeChild(this)}})})})([Element.prototype,CharacterData.prototype,DocumentType.prototype]);
(function(A){window.CMP=window.CMP||{};window.CMP.utils=function(){return{readData:function(l,u){l=l.dataset;var D=[];u=u.charAt(0).toUpperCase()+u.slice(1);u=["is","hook"+u];for(var f in l)if(Object.prototype.hasOwnProperty.call(l,f)){var k=l[f];0===f.indexOf("cmp")&&(f=f.slice(3),f=f.charAt(0).toLowerCase()+f.substring(1),-1===u.indexOf(f)&&(D[f]=k))}return D},setupProperties:function(l,u){var D={},f;for(f in u)if(Object.prototype.hasOwnProperty.call(u,f)){var k=u[f];D[f]=l&&null!=l[f]?k&&"function"===
typeof k.transform?k.transform(l[f]):l[f]:u[f]["default"]}return D}}}()})(window.document);
(function(A){window.CMP=window.CMP||{};window.CMP.image=window.CMP.image||{};window.CMP.image.dynamicMedia=function(){function l(e,p){for(var g=e.length,a=0;a<g-1&&e[a]<p;)a++;return void 0!==e[a]?e[a].toString():p}var u={},D=window.devicePixelRatio||1,f=function(e){var p=new XMLHttpRequest;e=e.split("{.width}")[0]+"?req\x3dset,json";p.open("GET",e,!1);p.onload=function(){if(200<=p.status&&400>p.status){var g=new RegExp(/^{[\s\S]*}$/gmi),a=(new RegExp(/^(?:\/\*jsonp\*\/)?\s*([^()]+)\(([\s\S]+),\s*"[0-9]*"\);?$/gmi)).exec(p.responseText),
d;a&&(a=a[2],g.test(a)&&(d=JSON.parse(a)));if(d&&d.set.relation&&0<d.set.relation.length)for(g=0;g<d.set.relation.length;g++)u[parseInt(d.set.relation[g].userdata.SmartCropWidth)]=":"+d.set.relation[g].userdata.SmartCropDef}};p.send();return u},k=function(e,p){for(var g=e.offsetWidth;20>g&&p&&!e._autoWidth;)g=p.offsetWidth,p=p.parentNode;return g};return{getAutoSmartCrops:f,getSrcSet:function(e,p){if(0<Object.keys(p).length){var g=[];for(var a in u)g.push(e.replace("{.width}",p[a])+" "+a+"w")}return g.join(",")},
getSrc:function(e,p){-1<e.indexOf("{.width}")&&(e=e.replace("{.width}",p));return e},setDMAttributes:function(e,p){var g=p.src.replace("dpr\x3doff","dpr\x3don,{dpr}");g=g.replace("{dpr}",D);var a={};"SmartCrop:Auto"===p.smartcroprendition&&(a=f(g));if(p.widths&&0<p.widths.length||0<Object.keys(a).length){var d=e.querySelector("img");e=k(e,e.parentNode);"SmartCrop:Auto"===p.smartcroprendition?(d.setAttribute("srcset",CMP.image.dynamicMedia.getSrcSet(g,a)),p=l(Object.keys(a,e)),d.setAttribute("src",
CMP.image.dynamicMedia.getSrc(g,a[p]))):(p=l(p.widths,e),d.setAttribute("src",CMP.image.dynamicMedia.getSrc(g,p)))}},getWidth:k}}();A.dispatchEvent(new CustomEvent("core.wcm.components.commons.site.image.dynamic-media.loaded"))})(window.document);
(function(){function A(e){function p(r){r.element.removeAttribute("data-cmp-is");r.options.src&&0<=r.options.src.indexOf("width\x3d{width}")&&(x=!0,B="width\x3d{width}");c._properties=CMP.utils.setupProperties(r.options,D);J(r.element);r.options.src&&Object.prototype.hasOwnProperty.call(r.options,"dmimage")&&"SmartCrop:Auto"===r.options.smartcroprendition&&(v=CMP.image.dynamicMedia.getAutoSmartCrops(r.options.src));c._elements.noscript&&(c._elements.container=c._elements.link?c._elements.link:c._elements.self,
q(),c._properties.lazy&&d(),c._elements.map&&c._elements.image.addEventListener("load",M),window.addEventListener("resize",I),"focus click load transitionend animationend scroll".split(" ").forEach(function(z){document.addEventListener(z,c.update)}),c._elements.image.addEventListener("cmp-image-redraw",c.update),c._interSectionObserver=new IntersectionObserver(function(z,E){z.forEach(function(C){0<C.intersectionRatio&&c.update()})}),c._interSectionObserver.observe(c._elements.self),c.update())}function g(){var r=
c._properties.widths&&0<c._properties.widths.length||0<Object.keys(v).length;if(0<Object.keys(v).length){var z=a(Object.keys(v),!1);z=v[z]}else z=r?(c._properties.dmimage?"":".")+a(c._properties.widths,!0):"";x&&(z=""!==z?"width\x3d"+z.substring(1):"");z=c._properties.src.replace(B,z);z=z.replace("{dpr}",f);var E=c._elements.image.getAttribute("src");if(z!==E)if(null===E||"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"===E)c._elements.image.setAttribute("src",z);else{var C=
c._properties.src.split(B),K=E.startsWith(C[0]);K&&1<C.length&&(K=E.endsWith(C[C.length-1]));K&&(c._elements.image.setAttribute("src",z),r||window.removeEventListener("scroll",c.update))}c._lazyLoaderShowing&&c._elements.image.addEventListener("load",m);c._interSectionObserver.unobserve(c._elements.self)}function a(r,z){for(var E=c._elements.self,C=E.clientWidth;0===C&&E.parentNode;)E=E.parentNode,C=E.clientWidth;z=C*(z?f:1);E=r.length;for(C=0;C<E-1&&r[C]<z;)C++;return r[C].toString()}function d(){var r=
c._elements.image.getAttribute("width"),z=c._elements.image.getAttribute("height");if(r&&z){var E=u.style;E["padding-bottom"]=z/r*100+"%";for(var C in E)Object.prototype.hasOwnProperty.call(E,C)&&(c._elements.image.style[C]=E[C])}c._elements.image.setAttribute("src","data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7");c._elements.image.classList.add(u.cssClass);c._lazyLoaderShowing=!0}function q(){var r=c._elements.noscript.textContent.trim();r=r.replace(/&(amp;)*lt;/g,
"\x3c");r=r.replace(/&(amp;)*gt;/g,"\x3e");r=(new DOMParser).parseFromString(r,"text/html");var z=r.querySelector(l.image);z.removeAttribute("src");c._elements.container.insertBefore(z,c._elements.noscript);(r=r.querySelector(l.map))&&c._elements.container.insertBefore(r,c._elements.noscript);c._elements.noscript.parentNode.removeChild(c._elements.noscript);c._elements.container.matches(l.image)?c._elements.image=c._elements.container:c._elements.image=c._elements.container.querySelector(l.image);
c._elements.map=c._elements.container.querySelector(l.map);c._elements.areas=c._elements.container.querySelectorAll(l.area)}function m(){c._elements.image.classList.remove(u.cssClass);for(var r in u.style)Object.prototype.hasOwnProperty.call(u.style,r)&&(c._elements.image.style[r]="");c._elements.image.removeEventListener("load",m);c._lazyLoaderShowing=!1}function F(){if(c._elements.areas&&0<c._elements.areas.length)for(var r=0;r<c._elements.areas.length;r++){var z=c._elements.image.width,E=c._elements.image.height;
if(z&&E){var C=c._elements.areas[r].dataset.cmpRelcoords;if(C){C=C.split(",");for(var K=Array(C.length),t=0;t<K.length;t++)K[t]=0===t%2?parseInt(C[t]*z):parseInt(C[t]*E);c._elements.areas[r].coords=K}}}}function J(r){c._elements={};c._elements.self=r;r=c._elements.self.querySelectorAll("[data-cmp-hook-image]");for(var z=0;z<r.length;z++){var E=r[z],C="image";C=C.charAt(0).toUpperCase()+C.slice(1);c._elements[E.dataset["cmpHook"+C]]=E}}function I(){c.update();F()}function M(){F()}var c=this,v={},x=
!1,B="{.width}";c.update=function(){if(c._properties.lazy){if(null===c._elements.container.offsetParent)var r=!1;else{r=window.pageYOffset;var z=r+document.documentElement.clientHeight,E=c._elements.container.getBoundingClientRect().top+r;r=E+c._elements.container.clientHeight>=r-c._properties.lazythreshold&&E<=z+c._properties.lazythreshold}r&&g()}else g()};e&&e.element&&p(e)}var l={self:'[data-cmp-is\x3d"image"]',image:'[data-cmp-hook-image\x3d"image"]',map:'[data-cmp-hook-image\x3d"map"]',area:'[data-cmp-hook-image\x3d"area"]'},
u={cssClass:"cmp-image__image--is-loading",style:{height:0,"padding-bottom":""}},D={widths:{"default":[],transform:function(e){var p=[];e.split(",").forEach(function(g){g=parseFloat(g);isNaN(g)||p.push(g)});return p}},lazy:{"default":!1,transform:function(e){return!(null===e||"undefined"===typeof e)}},dmimage:{"default":!1,transform:function(e){return!(null===e||"undefined"===typeof e)}},lazythreshold:{"default":0,transform:function(e){e=parseInt(e);return isNaN(e)?0:e}},src:{transform:function(e){return decodeURIComponent(e)}}},
f=window.devicePixelRatio||1,k="loading"!==document.readyState?Promise.resolve():new Promise(function(e){document.addEventListener("DOMContentLoaded",e)});Promise.all([k]).then(function(){for(var e=document.querySelectorAll(l.self),p=0;p<e.length;p++)new A({element:e[p],options:CMP.utils.readData(e[p],"image")});e=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;p=document.querySelector("body");(new e(function(g){g.forEach(function(a){a=[].slice.call(a.addedNodes);
0<a.length&&a.forEach(function(d){d.querySelectorAll&&[].slice.call(d.querySelectorAll(l.self)).forEach(function(q){new A({element:q,options:CMP.utils.readData(q,"image")})})})})})).observe(p,{subtree:!0,childList:!0,characterData:!0})})})();
(function(){function A(a){a=a.dataset;var d=[],q="search";q=q.charAt(0).toUpperCase()+q.slice(1);q=["is","hook"+q];for(var m in a)if(Object.prototype.hasOwnProperty.call(a,m)){var F=a[m];0===m.indexOf("cmp")&&(m=m.slice(3),m=m.charAt(0).toLowerCase()+m.substring(1),-1===q.indexOf(m)&&(d[m]=F))}return d}function l(a,d){a&&(!1!==d?(a.style.display="block",a.setAttribute("aria-hidden",!1)):(a.style.display="none",a.setAttribute("aria-hidden",!0)))}function u(a){var d=[];if(a&&a.elements)for(var q=0;q<
a.elements.length;q++){var m=a.elements[q];!m.disabled&&m.name&&(m=[m.name,encodeURIComponent(m.value)],d.push(m.join("\x3d")))}return d.join("\x26")}function D(a,d){if(a&&d)if(3===a.nodeType){var q=a.nodeValue;d=d.exec(q);if(q&&d){q=document.createElement("mark");q.className="cmp-search__item-mark";q.appendChild(document.createTextNode(d[0]));var m=a.splitText(d.index);m.nodeValue=m.nodeValue.substring(d[0].length);a.parentNode.insertBefore(q,m)}}else if(a.hasChildNodes())for(q=0;q<a.childNodes.length;q++)D(a.childNodes[q],
d)}function f(a){a.element&&a.element.removeAttribute("data-cmp-is");this._cacheElements(a.element);this._setupProperties(a.options);this._action=this._elements.form.getAttribute("action");this._resultsOffset=0;this._hasMoreResults=!0;this._elements.input.addEventListener("input",this._onInput.bind(this));this._elements.input.addEventListener("focus",this._onInput.bind(this));this._elements.input.addEventListener("keydown",this._onKeydown.bind(this));this._elements.clear.addEventListener("click",
this._onClearClick.bind(this));document.addEventListener("click",this._onDocumentClick.bind(this));this._elements.results.addEventListener("scroll",this._onScroll.bind(this));this._makeAccessible()}function k(){for(var a=document.querySelectorAll(e.self),d=0;d<a.length;d++)new f({element:a[d],options:A(a[d])});a=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;d=document.querySelector("body");(new a(function(q){q.forEach(function(m){m=[].slice.call(m.addedNodes);
0<m.length&&m.forEach(function(F){F.querySelectorAll&&[].slice.call(F.querySelectorAll(e.self)).forEach(function(J){new f({element:J,options:A(J)})})})})})).observe(d,{subtree:!0,childList:!0,characterData:!0})}var e={self:'[data-cmp-is\x3d"search"]',item:{self:'[data-cmp-hook-search\x3d"item"]',title:'[data-cmp-hook-search\x3d"itemTitle"]',focused:".cmp-search__item--is-focused"}},p={minLength:{"default":3,transform:function(a){a=parseFloat(a);return isNaN(a)?null:a}},resultsSize:{"default":10,transform:function(a){a=
parseFloat(a);return isNaN(a)?null:a}}},g=0;f.prototype._displayResults=function(){0===this._elements.input.value.length?(l(this._elements.clear,!1),this._cancelResults()):(this._elements.input.value.length<this._properties.minLength||this._updateResults(),l(this._elements.clear,!0))};f.prototype._onScroll=function(a){this._elements.results.scrollTop+2*this._elements.results.clientHeight>=this._elements.results.scrollHeight&&(this._resultsOffset+=this._properties.resultsSize,this._displayResults())};
f.prototype._onInput=function(a){var d=this;d._cancelResults();this._timeout=setTimeout(function(){d._displayResults()},300)};f.prototype._onKeydown=function(a){switch(a.keyCode){case 9:this._resultsOpen()&&(l(this._elements.results,!1),this._elements.input.setAttribute("aria-expanded","false"));break;case 13:a.preventDefault();this._resultsOpen()&&(a=this._elements.results.querySelector(e.item.focused))&&a.click();break;case 27:this._cancelResults();break;case 38:this._resultsOpen()&&(a.preventDefault(),
this._stepResultFocus(!0));break;case 40:this._resultsOpen()?(a.preventDefault(),this._stepResultFocus()):this._onInput()}};f.prototype._onClearClick=function(a){a.preventDefault();this._elements.input.value="";l(this._elements.clear,!1);l(this._elements.results,!1);this._elements.input.setAttribute("aria-expanded","false")};f.prototype._onDocumentClick=function(a){var d=this._elements.input.contains(a.target);a=this._elements.results.contains(a.target);d||a||(l(this._elements.results,!1),this._elements.input.setAttribute("aria-expanded",
"false"))};f.prototype._resultsOpen=function(){return"none"!==this._elements.results.style.display};f.prototype._makeAccessible=function(){var a="cmp-search-results-"+g;this._elements.input.setAttribute("aria-owns",a);this._elements.results.id=a;g++};f.prototype._generateItems=function(a,d){var q=this;a.forEach(function(m){var F=document.createElement("span");F.innerHTML=q._elements.itemTemplate.innerHTML;F.querySelectorAll(e.item.title)[0].appendChild(document.createTextNode(m.title));F.querySelectorAll(e.item.self)[0].setAttribute("href",
m.url);d.innerHTML+=F.innerHTML})};f.prototype._markResults=function(){var a=this._elements.results.querySelectorAll(e.item.self),d=this._elements.input.value.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$\x26");d=new RegExp("("+d+")","gi");for(var q=this._resultsOffset-1;q<a.length;++q)D(a[q],d)};f.prototype._stepResultFocus=function(a){var d=this._elements.results.querySelectorAll(e.item.self),q=this._elements.results.querySelector(e.item.focused);q=Array.prototype.indexOf.call(d,q);if(0<d.length)if(a){if(1<=
q&&(d[q].classList.remove("cmp-search__item--is-focused"),d[q].setAttribute("aria-selected","false"),d[q-1].classList.add("cmp-search__item--is-focused"),d[q-1].setAttribute("aria-selected","true")),a=this._elements.results.querySelector(e.item.focused))a=this._elements.results.scrollTop-a.offsetTop,0<a&&(this._elements.results.scrollTop-=a)}else if(0>q?(d[0].classList.add("cmp-search__item--is-focused"),d[0].setAttribute("aria-selected","true")):q+1<d.length&&(d[q].classList.remove("cmp-search__item--is-focused"),
d[q].setAttribute("aria-selected","false"),d[q+1].classList.add("cmp-search__item--is-focused"),d[q+1].setAttribute("aria-selected","true")),a=this._elements.results.querySelector(e.item.focused))a=a.offsetTop+a.offsetHeight-this._elements.results.scrollTop-this._elements.results.clientHeight,0<a?this._elements.results.scrollTop+=a:this._onScroll()};f.prototype._updateResults=function(){var a=this;if(a._hasMoreResults){var d=new XMLHttpRequest,q=a._action+"?"+u(a._elements.form)+"\x26resultsOffset\x3d"+
a._resultsOffset;d.open("GET",q,!0);d.onload=function(){setTimeout(function(){l(a._elements.loadingIndicator,!1);l(a._elements.icon,!0)},300);if(200<=d.status&&400>d.status){var m=JSON.parse(d.responseText);0<m.length?(a._generateItems(m,a._elements.results),a._markResults(),l(a._elements.results,!0),a._elements.input.setAttribute("aria-expanded","true")):a._hasMoreResults=!1;0<a._elements.results.querySelectorAll(e.item.self).length%a._properties.resultsSize&&(a._hasMoreResults=!1)}};l(a._elements.loadingIndicator,
!0);l(a._elements.icon,!1);d.send()}};f.prototype._cancelResults=function(){clearTimeout(this._timeout);this._resultsOffset=this._elements.results.scrollTop=0;this._hasMoreResults=!0;this._elements.results.innerHTML="";this._elements.input.setAttribute("aria-expanded","false")};f.prototype._cacheElements=function(a){this._elements={};this._elements.self=a;a=this._elements.self.querySelectorAll("[data-cmp-hook-search]");for(var d=0;d<a.length;d++){var q=a[d],m="search";m=m.charAt(0).toUpperCase()+
m.slice(1);this._elements[q.dataset["cmpHook"+m]]=q}};f.prototype._setupProperties=function(a){this._properties={};for(var d in p)if(Object.prototype.hasOwnProperty.call(p,d)){var q=p[d];this._properties[d]=a&&null!=a[d]?q&&"function"===typeof q.transform?q.transform(a[d]):a[d]:p[d]["default"]}};"loading"!==document.readyState?k():document.addEventListener("DOMContentLoaded",k)})();
(function(){function A(k){k=k.dataset;var e=[],p="formText";p=p.charAt(0).toUpperCase()+p.slice(1);p=["is","hook"+p];for(var g in k)if(Object.prototype.hasOwnProperty.call(k,g)){var a=k[g];0===g.indexOf("cmp")&&(g=g.slice(3),g=g.charAt(0).toLowerCase()+g.substring(1),-1===p.indexOf(g)&&(e[g]=a))}return e}function l(k){k.element&&k.element.removeAttribute("data-cmp-is");this._cacheElements(k.element);this._setupProperties(k.options);this._elements.input.addEventListener("invalid",this._onInvalid.bind(this));
this._elements.input.addEventListener("input",this._onInput.bind(this))}function u(){for(var k=document.querySelectorAll(D.self),e=0;e<k.length;e++)new l({element:k[e],options:A(k[e])});k=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;e=document.querySelector("body");(new k(function(p){p.forEach(function(g){g=[].slice.call(g.addedNodes);0<g.length&&g.forEach(function(a){a.querySelectorAll&&[].slice.call(a.querySelectorAll(D.self)).forEach(function(d){new l({element:d,
options:A(d)})})})})})).observe(e,{subtree:!0,childList:!0,characterData:!0})}var D={self:'[data-cmp-is\x3d"formText"]'},f={constraintMessage:"",requiredMessage:""};l.prototype._onInvalid=function(k){k.target.setCustomValidity("");k.target.validity.typeMismatch?this._properties.constraintMessage&&k.target.setCustomValidity(this._properties.constraintMessage):k.target.validity.valueMissing&&this._properties.requiredMessage&&k.target.setCustomValidity(this._properties.requiredMessage)};l.prototype._onInput=
function(k){k.target.setCustomValidity("")};l.prototype._cacheElements=function(k){this._elements={};this._elements.self=k;k=this._elements.self.querySelectorAll("[data-cmp-hook-form-text]");for(var e=0;e<k.length;e++){var p=k[e],g="formText";g=g.charAt(0).toUpperCase()+g.slice(1);this._elements[p.dataset["cmpHook"+g]]=p}};l.prototype._setupProperties=function(k){this._properties={};for(var e in f)if(Object.prototype.hasOwnProperty.call(f,e)){var p=f[e];this._properties[e]=k&&null!=k[e]?p&&"function"===
typeof p.transform?p.transform(k[e]):k[e]:f[e]["default"]}};"loading"!==document.readyState?u():document.addEventListener("DOMContentLoaded",u)})();
(function(){function A(){var k=0<document.querySelectorAll(f.sdkScript).length;window.adobe_dc_view_sdk||k||(k=document.createElement("script"),k.type="text/javascript",k.src="https://documentservices.adobe.com/view-sdk/viewer.js",document.body.appendChild(k))}function l(k){k.removeAttribute("data-cmp-is");A();k.dataset&&k.id&&(window.AdobeDC&&window.AdobeDC.View?u(k):document.addEventListener("adobe_dc_view_sdk.ready",function(){u(k)}))}function u(k){(new window.AdobeDC.View({clientId:k.dataset.cmpClientId,
divId:k.id+"-content",reportSuiteId:k.dataset.cmpReportSuiteId})).previewFile({content:{location:{url:k.dataset.cmpDocumentPath}},metaData:{fileName:k.dataset.cmpDocumentFileName}},JSON.parse(k.dataset.cmpViewerConfigJson))}function D(){for(var k=document.querySelectorAll(f.self),e=0;e<k.length;e++)l(k[e]);k=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;e=document.querySelector("body");(new k(function(p){p.forEach(function(g){g=[].slice.call(g.addedNodes);0<g.length&&
g.forEach(function(a){a.querySelectorAll&&[].slice.call(a.querySelectorAll(f.self)).forEach(function(d){l(d)})})})})).observe(e,{subtree:!0,childList:!0,characterData:!0})}var f={self:'[data-cmp-is\x3d"pdfviewer"]',sdkScript:'script[src\x3d"https://documentservices.adobe.com/view-sdk/viewer.js"]'};"loading"!==document.readyState?D():document.addEventListener("DOMContentLoaded",D)})();